version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:4000"
    environment:
      - PORT=4000
    depends_on:
      - mongo
      
  mongo:
    image: mongo
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db: